# Generated by Django 4.2.5 on 2024-06-03 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="isbn",
            new_name="ISBN",
        ),
    ]
